### ISSUE TITLE
Fix JpqlQueryParserTest for EclipseLink

### ISSUE THREAD

**Issue by CSchulz** [ArneLimburg/jpasecurity#65]
With Java 7:

  JpqlQueryParserTest.dtoConcatMultiParam:67->executeQuery:78 » Query 
Exception...
  JpqlQueryParserTest.dtoConcat:60->executeQuery:78 » Query 
Exception Descripti...

> Exception Description: An Exception was thrown while executing a ReportQuery with a constructor expression: java.lang.NoSuchMethodException: org.jpasecurity.dto.IdAndNameDto.<init>(int, java.lang.Boolean)
Internal Exception: java.lang.NoSuchMethodException: org.jpasecurity.dto.IdAndNameDto.<init>(int, java.lang.Boolean)
Query: ReportQuery(referenceClass=FieldAccessAnnotationTestBean jpql="SELECT new org.jpasecurity.dto.IdAndNameDto(tb.id, concat(tb.id, tb.name, tb.name, tb.name, tb.name, tb.name, tb.name, tb.name, tb.name)) FROM FieldAccessAnnotationTestBean tb WHERE EXISTS(SELECT tb2 FROM FieldAccessAnnotationTestBean tb2)")
	at java.lang.Class.getConstructor0(Class.java:2902)
	at java.lang.Class.getConstructor(Class.java:1731)
	at org.eclipse.persistence.internal.security.PrivilegedAccessHelper.getConstructorFor(PrivilegedAccessHelper.java:194)
	at org.eclipse.persistence.queries.ConstructorReportItem.initialize(ConstructorReportItem.java:200)
	at org.eclipse.persistence.queries.ReportQuery.prepare(ReportQuery.java:1063)
	at org.eclipse.persistence.queries.DatabaseQuery.checkPrepare(DatabaseQuery.java:673)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.checkPrepare(ObjectLevelReadQuery.java:911)
	at org.eclipse.persistence.queries.DatabaseQuery.checkPrepare(DatabaseQuery.java:622)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.buildEJBQLDatabaseQuery(EJBQueryImpl.java:194)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.buildEJBQLDatabaseQuery(EJBQueryImpl.java:116)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.<init>(EJBQueryImpl.java:102)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.<init>(EJBQueryImpl.java:86)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.createQuery(EntityManagerImpl.java:1614)
	at org.jpasecurity.persistence.JpqlQueryParserTest.executeQuery(JpqlQueryParserTest.java:78)
	at org.jpasecurity.persistence.JpqlQueryParserTest.dtoConcatMultiParam(JpqlQueryParserTest.java:67)

It seems with Java 7 the CONCAT is interpreted wrong and returns a Boolean.

**Comment by CSchulz** [comment]
Fixed with https://github.com/ArneLimburg/jpasecurity/pull/30/commits/b212e8d214b0d20a1dcd9239f999fc80ef3ee065
